### ISSUE TITLE
ESlint?

### ISSUE THREAD

**Issue by kerrykimrusso** [BeejLuig/currency-converter#15]
👍 / 👎? If the 👍 have it, then this issue will be to add it.

**Comment by BeejLuig** [comment]
I've never used Prettier, so curious: how tricky would it be to match eslint rules with Prettier formatting?

**Comment by BeejLuig** [comment]
Ok, I'm going to add eslint integration with the suggested defaults off. I use the google lint rules (tweaked) at work, so maybe we can start from there and make adjustments?

**Comment by BeejLuig** [comment]
Closing because PR #18 didn't do it automagically ¯\_(ツ)_/¯
