### ISSUE TITLE
if(mockAPI) or if(!mockAPI)

### ISSUE THREAD

**Issue by kerrykimrusso** [BeejLuig/currency-converter#19]
https://github.com/BeejLuig/currency-converter/blob/bf3f0d53c5b175447420cb6f0d070dabd162bf37/src/middleware/server.js#L11

The config for `dev` has `mockAPI: false` but I'd expect it to be `true`.

**Comment by BeejLuig** [comment]
Ahh you're right, the config is a hot mess.. I'll fix it
